### ISSUE TITLE
System module conflict

### ISSUE THREAD

**Issue by Supergran** [XoopsModules25x/userlog#4]
I've had conflicts with this on my test site so have just tried to deploy the module on a fresh install of the latest working 2.5.9 files on PHP.7.06 using Mambas latest iteration of the module.  
On install, the module appears installed on the modules summary as normal.  However, the system module logo no longer appears as it is now looking for an image at : modules/system/assets/images/logoModule.png rather than modules/system/images/system_slogo.png as before.  The link to the system module admin is also broken, linking instead to:  modules/system/admin/index.php which doesn't exist.  The system module version appears in red with a warning triangle with a tootip 'update'.  Updating the module has no effect.  Although the module appears installed the page tells me there is 1 module to install and if i click on that link it just shows userlog.
If I navigate to userlog admin via the main top menu the module settings appear to work and I can add setiings etc, however nothing ever gets logged.  The module concept looks excellent.  This looks as though it may be a minor file path issue having a big impact?

**Comment by mambax7** [comment]
Please download the current version from my repository: https://github.com/mambax7/userlog
Please set the logs to File
